# Generated by Django 4.1.3 on 2023-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=30)),
                ('flight_date', models.DateField()),
                ('flight_num', models.CharField(choices=[('XFA1', 'XFA1'), ('XFA2', 'XFA2'), ('XFA3', 'XFA3')], max_length=4)),
                ('inetx_ver', models.CharField(max_length=5)),
                ('cal_ver', models.CharField(max_length=5)),
                ('tspi_ch', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=4)),
                ('created_at', models.DateTimeField()),
                ('writer_name', models.CharField(max_length=10)),
            ],
        ),
    ]
